package com.example.goalachiever;

public enum GoalObjective {    
    CHILD_BIRTH,
    CHILD_EDUCATION,
    CHILD_MARRIAGE,
    CHILD_INHERITANCE,
    SELF_EDUCATION,
    SELF_MARRIAGE,
    SELF_HEALTH,
    SELF_TRAVEL,
    FAMILY_HEALTH,
    FAMILY_TRAVEL,
    EMERGENCY_COVERAGE,
    PROFESSIONAL_BREAK,
    EARLY_RETIREMENT,
    RETIREMENT_CORPUS,
    CREDIT_CARD_REPAYMENT,
    LOAN_REPAYMENT,
    ASSET_ACQUISITION,
    ENTREPRENUERSHIP,
    OTHER
}
