package com.example.goalachiever;

public enum GoalObjective {

    EARLY_RETIREMENT,
    RETIREMENT_CORPUS,
    CHILD_EDUCATION,
    SELF_EDUCATION,
    CHILD_MARRIAGE,
    SELF_MARRIAGE,
    SELF_HEALTH,
    FAMILY_HEALTH,
    EMERGENCY_COVERAGE,
    SELF_TRAVEL,
    FAMILY_TRAVEL,
    CREDIT_CARD_REPAYMENT,
    LOAN_REPAYMENT,
    ASSET_ACQUISITION,
    OTHER
}
