package com.example.goalachiever;

public enum InvestmentType {
    EQUITY_SHARES,
    EQUITY_MUTUAL_FUNDS,
    PPF_EPF_VPF_GPF,
    NATIONAL_PENSION_SCHEME,
    FIXED_DEPOSITS,
    TERM_INSURANCE,
    ULIP,
    GOLD_PHYSICAL,
    GOLD_ETF,
    GOLD_MUTUAL_FUND,
    SOVERIGN_GOLD_BONDS,
    COMMODITIES,
    DEBENTURES,
    DEBT_MUTUAL_FUNDS,
    REAL_ESTATE,
    BONDS_GOVT_TREASURY,
    SYSTEMATIC_INVESTMENT_PLAN,
    CASH_AT_HAND,
    OTHER
}
